Repository duckduckgo/apple-browsers, pull requests merged in 2025-07, with the labels that each got.

#1293 Add pixel schema for iOS and macOS
  .github/workflows/pixel_validation.yml
  .github/workflows/privacy-review.yml
  iOS/PixelDefinitions/ignore_params.json5
  iOS/PixelDefinitions/native_experiments.json5
  iOS/PixelDefinitions/params_dictionary.json5
  iOS/PixelDefinitions/pixels/TEMPLATE.json5
  iOS/PixelDefinitions/suffixes_dictionary.json5
  iOS/package-lock.json
  iOS/package.json
  macOS/PixelDefinitions/ignore_params.json5
  macOS/PixelDefinitions/native_experiments.json5
  macOS/PixelDefinitions/params_dictionary.json5
  macOS/PixelDefinitions/pixels/TEMPLATE.json5
  macOS/PixelDefinitions/suffixes_dictionary.json5
  macOS/package-lock.json
  macOS/package.json
Labels: privacy review required

#1321 macOS: Pixels for the CPM/Autoconsent feature.
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Autoconsent/AutoconsentManagement.swift
  macOS/DuckDuckGo/Autoconsent/AutoconsentPixels.swift
  macOS/DuckDuckGo/Autoconsent/AutoconsentUserScript.swift
  macOS/PixelDefinitions/pixels/autoconsent.json5
Labels: privacy review required

#1095 Refactor favicon logic into TabContent+DisplayedFavicon extension
  DuckDuckGo.xcworkspace/xcshareddata/swiftpm/Package.resolved
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/PinnedTabs/View/PinnedTabView.swift
  macOS/DuckDuckGo/RecentlyClosed/View/RecentlyClosedMenu.swift
  macOS/DuckDuckGo/Tab/Model/TabContent+DisplayedFavicon.swift
  macOS/DuckDuckGo/Tab/Navigation/DuckURLSchemeHandler.swift
  macOS/DuckDuckGo/Tab/TabExtensions/FaviconsTabExtension.swift
  macOS/DuckDuckGo/Tab/ViewModel/TabContent+DisplayedFavicon.swift
  macOS/DuckDuckGo/Tab/ViewModel/TabViewModel.swift
  macOS/IntegrationTests/Tab/AddressBarTests.swift
  macOS/LocalPackages/AppKitExtensions/Sources/AppKitExtensions/NSImageExtension.swift
  macOS/UnitTests/Common/Extensions/XCTestCaseExtension.swift
  macOS/UnitTests/Menus/MoreOptionsMenuTests.swift
  macOS/UnitTests/PinnedTabs/PinnedTabsViewModelTests.swift
  macOS/UnitTests/Tab/ViewModel/TabViewModelTests.swift
  macOS/UnitTests/YoutubePlayer/DuckPlayerTests.swift
Labels: enhancement, merge on approve

#1359 Define Pixels for VPN upsell
  macOS/DuckDuckGo/Statistics/PrivacyProPixel.swift
  macOS/PixelDefinitions/pixels/privacy_pro_toolbar_button.json5
Labels: privacy review required

#1396 iOS: Pixels for the CPM feature
  iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
  iOS/DuckDuckGo/Autoconsent/AutoconsentManagement.swift
  iOS/DuckDuckGo/Autoconsent/AutoconsentPixels.swift
  iOS/DuckDuckGo/Autoconsent/AutoconsentUserScript.swift
  iOS/DuckDuckGo/TabViewController.swift
  iOS/PixelDefinitions/params_dictionary.json5
  iOS/PixelDefinitions/pixels/autoconsent.json5
  iOS/PixelDefinitions/suffixes_dictionary.json5
Labels: privacy review required

#1333 Authentication change subscription message
  SharedPackages/BrowserServicesKit/Sources/Subscription/SubscriptionUserScript/SubscriptionUserScript.swift
  SharedPackages/BrowserServicesKit/Sources/SubscriptionTestingUtilities/SubscriptionUserScript/MockSubscriptionUserScriptHandler.swift
  SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionUserScript/SubscriptionUserScriptHandlerTests.swift
  SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionUserScript/SubscriptionUserScriptTests.swift
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Tab/TabExtensions/SubscriptionTabExtension.swift
  macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift
  macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeatureV2.swift
Labels: stale

#1459 iOS: Fix failing fingerprinting test
  iOS/DuckDuckGo/BrowsingMenu/BrowsingMenuViewController.storyboard
  iOS/FingerprintingUITests/FingerprintUITest.swift
Labels: merge on approve

#1486 iOS: Add new pink app icon
  iOS/DuckDuckGo/AlternateAppIcons.xcassets/AppIcon-pink.appiconset/Contents.json
  iOS/DuckDuckGo/AlternateAppIcons.xcassets/AppIcon-pink.appiconset/Icon-Dark-Pink-1024x1024.png
  iOS/DuckDuckGo/AlternateAppIcons.xcassets/AppIcon-pink.appiconset/Icon-Light-Pink-1024x1024.png
  iOS/DuckDuckGo/AlternateAppIcons.xcassets/AppIcon-pink.appiconset/Icon-Tinted-1024x1024.png
  iOS/DuckDuckGo/AlternateAppIcons.xcassets/UIAssets/AppIcon-pink-medium.imageset/AppIconPink60x60@2x.png
  iOS/DuckDuckGo/AlternateAppIcons.xcassets/UIAssets/AppIcon-pink-medium.imageset/AppIconPink60x60@3x.png
  iOS/DuckDuckGo/AlternateAppIcons.xcassets/UIAssets/AppIcon-pink-medium.imageset/Contents.json
  iOS/DuckDuckGo/AlternateAppIcons.xcassets/UIAssets/AppIcon-pink-small.imageset/AppIconPink29x29@2x.png
  iOS/DuckDuckGo/AlternateAppIcons.xcassets/UIAssets/AppIcon-pink-small.imageset/AppIconPink29x29@3x.png
  iOS/DuckDuckGo/AlternateAppIcons.xcassets/UIAssets/AppIcon-pink-small.imageset/Contents.json
  iOS/DuckDuckGo/AppIcon.swift
  iOS/DuckDuckGo/OnboardingExperiment/AddToDock/AddToDockPromoViewModel.swift
  iOS/DuckDuckGoTests/AppIconPickerViewModelTests.swift
Labels: merge on approve

#734 Add ability to dismiss the save prompt by tapping the nav bar popover button
  macOS/DuckDuckGo/NavigationBar/View/NavigationBarPopovers.swift
Labels: stale
