Repository duckduckgo/apple-browsers, pull requests merged in 2025-08, with the labels that each got.

#1567 [iOS] widget usage reporting
  SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
  iOS/Core/FeatureFlag.swift
  iOS/Core/PixelEvent.swift
  iOS/DuckDuckGo/AppLifecycle/AppStates/Launching.swift
  iOS/DuckDuckGo/AppServices/ReportingService.swift
  iOS/PixelDefinitions/params_dictionary.json5
  iOS/PixelDefinitions/pixels/widget_reporting.json5
  iOS/PixelDefinitions/suffixes_dictionary.json5
Labels: privacy review required

#1607 Global AI Switch 4. Pixels
  macOS/DuckDuckGo/AIChat/AIChatPixel.swift
  macOS/DuckDuckGo/Preferences/View/PreferencesAIChat.swift
  macOS/PixelDefinitions/pixels/aichat_settings_pixels.json5
Labels: privacy review required

#1632 New Tab Page metrics adjusted for New Tab Page per tab
  SharedPackages/BrowserServicesKit/Sources/Navigation/NavigationResponder.swift
  macOS/DuckDuckGo/NewTabPage/NewTabPageCoordinator.swift
  macOS/DuckDuckGo/Tab/Model/Tab+Navigation.swift
  macOS/DuckDuckGo/Tab/Model/Tab.swift
  macOS/DuckDuckGo/Tab/TabExtensions/NewTabPageTabExtension.swift
  macOS/DuckDuckGo/Tab/TabExtensions/TabExtensions.swift
  macOS/DuckDuckGo/Tab/View/BrowserTabViewController.swift
  macOS/UnitTests/TabExtensionsTests/NewTabPageTabExtensionTests.swift
Labels: merge on approve

#1581 Subscription keychain error 25291 mitigation
  SharedPackages/BrowserServicesKit/Sources/Common/OSStatus+HumanReadableDescription.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/AuthMigrator.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/Storage/V2/KeychainManager.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/Storage/V2/KeychainOperationsProviding.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/Storage/V2/SubscriptionTokenKeychainStorageV2.swift
  SharedPackages/BrowserServicesKit/Sources/SubscriptionTestingUtilities/MockPixelHandler.swift
  SharedPackages/BrowserServicesKit/Sources/SubscriptionTestingUtilities/Storage/KeychainOperationsMock.swift
  SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Managers/AuthMigratorTests.swift
  SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Storage/KeychainManagerTests.swift
  SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Storage/SubscriptionTokenKeychainStorageV2Tests.swift
  iOS/Core/PixelEvent.swift
  iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
  iOS/DuckDuckGo/AppLifecycle/AppDependencyProvider.swift
  iOS/DuckDuckGo/Subscription/SubscriptionPixelHandler.swift
  iOS/PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift
  iOS/PixelDefinitions/pixels/subscription.json5
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Application/AppDelegate.swift
  macOS/DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/MacPacketTunnelProvider.swift
  macOS/DuckDuckGo/Statistics/PrivacyProPixel.swift
  macOS/DuckDuckGo/Subscription/SubscriptionManager+StandardConfiguration.swift
  macOS/DuckDuckGo/Subscription/SubscriptionPixelHandler.swift
  macOS/DuckDuckGoDBPBackgroundAgent/DuckDuckGoDBPBackgroundAgentAppDelegate.swift
  macOS/PixelDefinitions/pixels/subscription.json5
  macOS/UnitTests/RemoteMessaging/RemoteMessagingConfigMatcherProviderTests.swift
Labels: privacy review required

#1620 Startup pixels
  iOS/Core/DailyPixel.swift
  iOS/Core/PixelEvent.swift
  iOS/DuckDuckGo/AppConfiguration/AppConfiguration.swift
  iOS/DuckDuckGo/AppConfiguration/PersistentStoresConfiguration.swift
  iOS/DuckDuckGo/AppLifecycle/AppStateMachine.swift
  iOS/DuckDuckGo/AppLifecycle/AppStates/Launching.swift
  iOS/DuckDuckGo/AppLifecycle/AppStates/Terminating.swift
  iOS/DuckDuckGo/AppServices/AppKeyValueFileStoreService.swift
  iOS/DuckDuckGo/BookmarksDatabaseSetup.swift
  iOS/DuckDuckGo/TabsModelPersistence.swift
  iOS/DuckDuckGo/UICoordination/MainCoordinator.swift
  iOS/DuckDuckGoTests/AppStateMachineTests.swift
  iOS/PixelDefinitions/pixels/crash_pixels.json5
  iOS/PixelDefinitions/pixels/startup_pixels.json5
  iOS/PixelDefinitions/suffixes_dictionary.json5
Labels: privacy review required

#1647 [Release PR] Update Sparkle error pixel to include reason string
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Statistics/GeneralPixel.swift
  macOS/DuckDuckGo/Updates/UpdateController.swift
  macOS/LocalPackages/BuildToolPlugins/Plugins/InputFilesChecker/InputFilesChecker.swift
  macOS/PixelDefinitions/pixels/debug_sparkle.json5
  macOS/UnitTests/Updates/UpdateControllerTests.swift
Labels: privacy review required

#1652 migrate AI Chat settings to shared user defaults - app-configuration
  iOS/Core/ContentBlockerStoreConstants.swift
  iOS/Core/EtagStorage.swift
  iOS/Core/PixelEvent.swift
  iOS/Core/global.swift
  iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
  iOS/DuckDuckGo/AIChat/AIChatSettings.swift
  iOS/DuckDuckGo/AIChat/AIChatSettingsMigration.swift
  iOS/DuckDuckGo/AppConfiguration/AppConfiguration.swift
  iOS/DuckDuckGo/AppConfiguration/PixelConfiguration.swift
  iOS/DuckDuckGo/AppLifecycle/AppStates/Launching.swift
  iOS/DuckDuckGo/Configuration/ConfigurationManager.swift
  iOS/DuckDuckGo/DebugEtagStorage.swift
  iOS/DuckDuckGo/DuckDuckGo.entitlements
  iOS/DuckDuckGoTests/AIChat/AIChatSettingsMigrationTests.swift
  iOS/DuckDuckGoTests/AIChat/AIChatSettingsTests.swift
  iOS/PacketTunnelProvider/NetworkProtection/ConfigurationStore.swift
  iOS/PixelDefinitions/pixels/ai_chat_settings_migration.json5
  iOS/Widgets/WidgetsExtension.entitlements
Labels: privacy review required

#1670 Improve Dax logo alignment during experimental address bar transition
  iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/DaxLogoManager.swift
  iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift
  iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/Transition/MainViewEditingStateTransitioning.swift
  iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/Transition/OmniBarEditingStateTransition.swift
  iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/Transition/OmniBarEditingStateTransitioning.swift
  iOS/DuckDuckGo/MainViewController.swift
Labels: merge on approve

#1587 Send subscription error values through to PixelKit
  SharedPackages/BrowserServicesKit/Sources/Subscription/Flows/AppStore/AppStorePurchaseFlow.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/Flows/AppStore/AppStorePurchaseFlowV2.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/Flows/Stripe/StripePurchaseFlow.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/Flows/Stripe/StripePurchaseFlowV2.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/StorePurchaseManager/StorePurchaseManager.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/StorePurchaseManager/StorePurchaseManagerV2.swift
  SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Flows/AppStorePurchaseFlowV2Tests.swift
  SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/Flows/StripePurchaseFlowTests.swift
  SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/PrivacyProSubscriptionV2IntegrationTests.swift
  iOS/DuckDuckGoTests/Subscription/StorePurchaseManagerTests.swift
  iOS/DuckDuckGoTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift
  macOS/DuckDuckGo/Statistics/PrivacyProPixel.swift
  macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionErrorReporter.swift
  macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeature.swift
  macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeatureV2.swift
  macOS/PixelDefinitions/params_dictionary.json5
  macOS/PixelDefinitions/pixels/subscription.json5
  macOS/PixelDefinitions/pixels/vpn_sub_access_revoked_pixels.json5
  macOS/UnitTests/Subscription/SubscriptionErrorReporterTests.swift
  macOS/UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureForStripeTests.swift
  macOS/UnitTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift
Labels: privacy review required

#1699 VPN latency pixel parameter update
  SharedPackages/VPN/Sources/VPN/Diagnostics/NetworkProtectionLatencyMonitor.swift
  SharedPackages/VPN/Sources/VPN/PacketTunnelProvider.swift
  SharedPackages/VPN/Sources/VPN/Settings/VPNSettings.swift
  iOS/PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift
  iOS/PixelDefinitions/pixels/vpn_latency.json5
  macOS/DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/MacPacketTunnelProvider.swift
  macOS/PixelDefinitions/pixels/vpn_latency.json5
Labels: privacy review required

#1713 macOS: Open Fire Window by default
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Application/AppDelegate.swift
  macOS/DuckDuckGo/Application/Application.swift
  macOS/DuckDuckGo/Common/Localizables/UserText.swift
  macOS/DuckDuckGo/Common/Utilities/UserDefaultsWrapper.swift
  macOS/DuckDuckGo/Fire/Model/Fire.swift
  macOS/DuckDuckGo/Fire/Model/VisualizeFireSettingsDecider.swift
  macOS/DuckDuckGo/Fire/View/FireCoordinator.swift
  macOS/DuckDuckGo/Fire/View/FireViewController.swift
  macOS/DuckDuckGo/Fire/ViewModel/FireViewModel.swift
  macOS/DuckDuckGo/Localization/Localizable.xcstrings
  macOS/DuckDuckGo/MainWindow/MainViewController.swift
  macOS/DuckDuckGo/Menus/ApplicationDockMenu.swift
  macOS/DuckDuckGo/Menus/MainMenu.swift
  macOS/DuckDuckGo/Menus/MainMenuActions.swift
  macOS/DuckDuckGo/NavigationBar/View/MoreOptionsMenu.swift
  macOS/DuckDuckGo/NewTabPage/NewTabPageActionsManagerExtension.swift
  macOS/DuckDuckGo/NewTabPage/NewTabPageCoordinator.swift
  macOS/DuckDuckGo/Preferences/Model/DataClearingPreferences.swift
  macOS/DuckDuckGo/Preferences/View/PreferencesDataClearingView.swift
  macOS/DuckDuckGo/Preferences/View/PreferencesGeneralView.swift
  macOS/DuckDuckGo/Windows/View/WindowControllersManager.swift
  macOS/DuckDuckGo/Windows/View/WindowsManager.swift
  macOS/IntegrationTests/App/WindowManagerStateRestorationTests.swift
  macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
  macOS/UnitTests/AppDelegate/AutoClearHandlerTests.swift
  macOS/UnitTests/Fire/DefaultVisualizeFireSettingsDeciderTests.swift
  macOS/UnitTests/Fire/VisualizeFireAnimationDeciderTests.swift
  macOS/UnitTests/Menus/MainMenuTests.swift
  macOS/UnitTests/Menus/MoreOptionsMenuTests.swift
  macOS/UnitTests/Preferences/DataClearingPreferencesTests.swift
Labels: pending ship review

#1731 [iOS] Add Push Notification Pixel Definition
  iOS/PixelDefinitions/pixels/push-notification.json5
Labels: privacy review required

#1777 iOS: Add Experimental Omnibar Pixels for Duck.ai Usage Measurement
  iOS/Core/PixelEvent.swift
  iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift
  iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/SwitchBarHandler.swift
  iOS/DuckDuckGo/MainViewController.swift
  iOS/DuckDuckGo/OmniBarViewController.swift
  iOS/PixelDefinitions/pixels/experimental_omnibar_metrics.json5
Labels: privacy review required
