Repository duckduckgo/apple-browsers, pull requests merged in 2025-10, with the labels that each got.

#2001 Add comprehensive pixel tracking for App Store update flow
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Menus/MainMenuActions.swift
  macOS/DuckDuckGo/NavigationBar/View/MoreOptionsMenu.swift
  macOS/DuckDuckGo/Preferences/Model/AboutPreferences.swift
  macOS/DuckDuckGo/Updates/AppStore/AppStoreUpdateController.swift
  macOS/DuckDuckGo/Updates/AppStore/CheckForUpdatesAppStorePixels.swift
  macOS/DuckDuckGo/Updates/LatestReleaseChecker.swift
  macOS/DuckDuckGo/Updates/UpdateController.swift
  macOS/DuckDuckGo/Updates/UpdateFlowPixels.swift
  macOS/DuckDuckGo/Updates/UpdateNotificationPresenter.swift
  macOS/PixelDefinitions/pixels/check_for_updates_app_store_pixels.json5
  macOS/PixelDefinitions/pixels/update_flow_pixels.json5
  macOS/UnitTests/Updates/CheckForUpdatesAppStorePixelsTests.swift
Labels: privacy review required

#2052 Implements Theme Switcher UI: Mark 1
  macOS/DuckDuckGo/Preferences/View/PreferencesAppearanceView.swift
  macOS/DuckDuckGo/Preferences/View/PreferencesRootView.swift
  macOS/LocalPackages/SwiftUIExtensions/Sources/SwiftUIExtensions/Image+Named.swift
  macOS/LocalPackages/SwiftUIExtensions/Sources/SwiftUIExtensions/SlidingPickerView.swift
  macOS/LocalPackages/SwiftUIExtensions/Sources/SwiftUIExtensions/View+Metrics.swift
Labels: enhancement

#2076 Add site-loading success rate pixels.
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Statistics/SiteLoadingPixel.swift
  macOS/DuckDuckGo/Tab/TabExtensions/NavigationPixelNavigationResponder.swift
  macOS/PixelDefinitions/params_dictionary.json5
  macOS/PixelDefinitions/pixels/navigation.json5
Labels: privacy review required

#2054 Implements Theme Switcher UI: Mark 2
  macOS/DuckDuckGo/Preferences/View/PreferencesAppearanceView.swift
  macOS/LocalPackages/SwiftUIExtensions/Sources/SwiftUIExtensions/SlidingPickerView.swift
Labels: enhancement

#2077 Dynamic Theme Support: Tab Bar
  SharedPackages/DesignResourcesKit/Sources/DesignResourcesKit/Colors/SharedPalettes/SharedDefaultColorPalette.swift
  macOS/DuckDuckGo/MainWindow/MainViewController.swift
  macOS/DuckDuckGo/MainWindow/MainWindowController.swift
  macOS/DuckDuckGo/PinnedTabs/View/PinnedTabView.swift
  macOS/DuckDuckGo/PinnedTabs/View/PinnedTabsView.swift
  macOS/DuckDuckGo/Tab/View/RampView.swift
  macOS/DuckDuckGo/Tab/ViewModel/TabContent+DisplayedFavicon.swift
  macOS/DuckDuckGo/Tab/ViewModel/TabViewModel.swift
  macOS/DuckDuckGo/TabBar/View/TabBarFooter.swift
  macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift
  macOS/DuckDuckGo/TabBar/View/TabBarViewItem.swift
  macOS/DuckDuckGo/Windows/View/WindowsManager.swift
  macOS/IntegrationTests/App/WindowManagerStateRestorationTests.swift
  macOS/IntegrationTests/Downloads/DownloadListCoordinatorTests.swift
  macOS/IntegrationTests/Onboarding/BrowserTabViewControllerOnboardingTests.swift
  macOS/IntegrationTests/Onboarding/OnboardingNavigatingTests.swift
  macOS/UnitTests/Bookmarks/Model/ContextualMenuTests.swift
  macOS/UnitTests/HomePage/HomePageSettingsModelTests.swift
  macOS/UnitTests/NewTabPage/NewTabPageShownPixelSenderTests.swift
  macOS/UnitTests/Onboarding/ContextualOnboarding/ContextualDaxDialogsFactoryTests.swift
  macOS/UnitTests/Onboarding/ContextualOnboarding/OnboardingFireButtonDialogViewModelTests.swift
  macOS/UnitTests/Tab/ViewModel/TabViewModelTests.swift
Labels: enhancement

#2079 Dynamic Theme Support: Preferences + Downloads
  macOS/DuckDuckGo/Common/View/SwiftUI/BannerView.swift
  macOS/DuckDuckGo/FileDownload/View/DownloadsViewController.swift
  macOS/DuckDuckGo/NavigationBar/View/Animations/BadgeAnimations/CookieManaged/CookieNotificationAnimationModel.swift
  macOS/DuckDuckGo/NavigationBar/View/MoreOptionsMenu.swift
  macOS/DuckDuckGo/Preferences/Model/PreferencesSidebarModel.swift
  macOS/DuckDuckGo/Preferences/View/PreferencesRootView.swift
Labels: enhancement

#2086 Dynamic Theme Support: Address Bar Buttons
  macOS/DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift
Labels: enhancement

#2081 Add PIR wide events
  SharedPackages/BrowserServicesKit/Sources/PixelKit/WideEvent/PIR/OptOutConfirmationWideEventData.swift
  SharedPackages/BrowserServicesKit/Sources/PixelKit/WideEvent/PIR/OptOutSubmissionWideEventData.swift
  SharedPackages/BrowserServicesKit/Sources/PixelKit/WideEvent/WideEvent.swift
  SharedPackages/BrowserServicesKit/Sources/PixelKit/WideEvent/WideEventData.swift
  SharedPackages/BrowserServicesKit/Sources/PixelKit/WideEvent/WideEventParameters.swift
  SharedPackages/BrowserServicesKit/Sources/PixelKitTestingUtilities/WideEventMock.swift
  SharedPackages/DataBrokerProtectionCore/Package.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/BrokerProfileJobDependencies.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/EmailConfirmationJob.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/EmailConfirmationJobDependencies.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/RecordFoundDateResolver.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/SubJob/BrokerProfileOptOutSubJob.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/SubJob/BrokerProfileScanSubJob.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/WideEvent/OptOutConfirmationWideEventEmitter.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/WideEvent/OptOutSubmissionWideEventRecorder.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Pixels/DataBrokerProtectionStageDurationCalculator.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/SecureVaultStorage/DataBrokerProtectionDatabase.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCoreTestsUtils/Mocks.swift
  SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/DataBrokerProtectionStageDurationCalculatorTests.swift
  SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/OptOutConfirmationWideEventEmitterTests.swift
  SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/OptOutSubmissionWideEventRecorderTests.swift
  SharedPackages/DataBrokerProtectionCore/Tests/DataBrokerProtectionCoreTests/RecordFoundDateResolverTests.swift
  iOS/DuckDuckGo/AppServices/DBPService.swift
  iOS/LocalPackages/DataBrokerProtection-iOS/Sources/DataBrokerProtection-iOS/ManagingAndCoordinating/DataBrokerProtectionIOSManagerProvider.swift
  iOS/PixelDefinitions/params_dictionary.json5
  iOS/PixelDefinitions/pixels/data_broker_protection.json5
  iOS/PixelDefinitions/pixels/wide_pixel.json5
  macOS/DuckDuckGoDBPBackgroundAgent/DuckDuckGoDBPBackgroundAgentAppDelegate.swift
  macOS/LocalPackages/DataBrokerProtection-macOS/Sources/DataBrokerProtection-macOS/BackgroundAgent/DataBrokerProtectionAgentManager.swift
  macOS/PixelDefinitions/params_dictionary.json5
  macOS/PixelDefinitions/pixels/data_broker_protection.json5
  macOS/PixelDefinitions/pixels/wide_pixel.json5
Labels: privacy review required

#2111 Fixes edge case where Restart to Update button does nothing
  macOS/DuckDuckGo/Statistics/GeneralPixel.swift
  macOS/DuckDuckGo/Updates/Sparkle/ReleaseNotesTabExtension.swift
  macOS/DuckDuckGo/Updates/Sparkle/SparkleUpdateController.swift
  macOS/PixelDefinitions/pixels/update_pixels.json5
Labels: privacy review required

#2104 Renames ThemeManager Protocol
  macOS/DuckDuckGo/AIChat/Sidebar/AIChatSidebarViewController.swift
  macOS/DuckDuckGo/Bookmarks/Model/BookmarkOutlineViewDataSource.swift
  macOS/DuckDuckGo/Bookmarks/View/BookmarkListViewController.swift
  macOS/DuckDuckGo/Bookmarks/View/BookmarkManagementDetailViewController.swift
  macOS/DuckDuckGo/Bookmarks/View/BookmarkManagementSidebarViewController.swift
  macOS/DuckDuckGo/Bookmarks/View/BookmarkOutlineCellView.swift
  macOS/DuckDuckGo/Bookmarks/View/BookmarkTableCellView.swift
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCollectionViewItem.swift
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarMenuViewController.swift
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarViewController.swift
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarViewModel.swift
  macOS/DuckDuckGo/FileDownload/View/DownloadsViewController.swift
  macOS/DuckDuckGo/Fire/View/FirePopoverViewController.swift
  macOS/DuckDuckGo/Fire/View/FireViewController.swift
  macOS/DuckDuckGo/MainWindow/MainViewController.swift
  macOS/DuckDuckGo/MainWindow/MainWindowController.swift
  macOS/DuckDuckGo/NavigationBar/View/AddressBarButtonsViewController.swift
  macOS/DuckDuckGo/NavigationBar/View/AddressBarTextField.swift
  macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift
  macOS/DuckDuckGo/NavigationBar/View/Animations/BadgeAnimations/CookieManaged/CookieNotificationAnimationModel.swift
  macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
  macOS/DuckDuckGo/NetworkProtection/AppTargets/BothAppTargets/NetworkProtectionNavBarButtonModel.swift
  macOS/DuckDuckGo/NewTabPage/Features/Customization/NewTabPageCustomizationModel.swift
  macOS/DuckDuckGo/RemoteMessaging/RemoteMessagingClient.swift
  macOS/DuckDuckGo/RemoteMessaging/RemoteMessagingConfigMatcherProvider.swift
  macOS/DuckDuckGo/SecureVault/View/PasswordManagementViewController.swift
  macOS/DuckDuckGo/Suggestions/View/SuggestionTableCellView.swift
  macOS/DuckDuckGo/Suggestions/View/SuggestionTableRowView.swift
  macOS/DuckDuckGo/Suggestions/View/SuggestionViewController.swift
  macOS/DuckDuckGo/Suggestions/ViewModel/SuggestionContainerViewModel.swift
  macOS/DuckDuckGo/Suggestions/ViewModel/SuggestionViewModel.swift
  macOS/DuckDuckGo/TabBar/View/TabBarFooter.swift
  macOS/DuckDuckGo/TabBar/View/TabBarViewController.swift
  macOS/DuckDuckGo/TabBar/View/TabBarViewItem.swift
  macOS/DuckDuckGo/VisualRefresh/ThemeManager.swift
  macOS/UnitTests/HomePage/HomePageSettingsModelTests.swift
  macOS/UnitTests/NewTabPage/NewTabPageCoordinatorTests.swift
  macOS/UnitTests/NewTabPage/NewTabPageShownPixelSenderTests.swift
  macOS/UnitTests/VisualRefresh/MockThemeManager.swift
Labels: enhancement

#2106 Dynamic Theme Support: Popovers
  macOS/DuckDuckGo/Bookmarks/View/BookmarkListPopover.swift
  macOS/DuckDuckGo/Common/Extensions/NSPopoverExtension.swift
  macOS/DuckDuckGo/FileDownload/View/DownloadsPopover.swift
  macOS/DuckDuckGo/SecureVault/View/PasswordManagementPopover.swift
  macOS/DuckDuckGo/VisualRefresh/ColorsProviding.swift
Labels: enhancement

#2080 AuthV2 refresh & adoption events
  SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
  SharedPackages/BrowserServicesKit/Sources/Networking/Auth/OAuthClient.swift
  SharedPackages/BrowserServicesKit/Sources/NetworkingTestingUtils/MockOAuthClient.swift
  SharedPackages/BrowserServicesKit/Sources/PixelKit/WideEvent/WideEvent.swift
  SharedPackages/BrowserServicesKit/Sources/PixelKit/WideEvent/WideEventData.swift
  SharedPackages/BrowserServicesKit/Sources/PixelKit/WideEvent/WideEventError.swift
  SharedPackages/BrowserServicesKit/Sources/PixelKit/WideEvent/WideEventParameters.swift
  SharedPackages/BrowserServicesKit/Sources/PixelKitTestingUtilities/WideEventMock.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/Managers/SubscriptionManagerV2.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/WideEvents/AuthV2TokenAdoptionWideEventData.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/WideEvents/AuthV2TokenRefreshWideEventData.swift
  SharedPackages/BrowserServicesKit/Sources/Subscription/WideEvents/SubscriptionPurchaseWideEventData.swift
  SharedPackages/BrowserServicesKit/Tests/BrowserServicesKitTests/Subscription/SubscriptionFeatureAvailabilityTests.swift
  SharedPackages/BrowserServicesKit/Tests/NetworkingTests/Auth/OAuthClientTests.swift
  SharedPackages/BrowserServicesKit/Tests/PixelKitTests/WideEventTests.swift
  SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/AuthV2WideEventTests.swift
  SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/DuckDuckGoSubscriptionV2IntegrationTests.swift
  SharedPackages/BrowserServicesKit/Tests/SubscriptionTests/SubscriptionWideEventTests.swift
  iOS/Core/FeatureFlag.swift
  iOS/DuckDuckGo/AppLifecycle/AppDependencyProvider.swift
  iOS/DuckDuckGo/AppLifecycle/AppStates/Launching.swift
  iOS/DuckDuckGo/Subscription/UserScripts/SubscriptionPagesUseSubscriptionFeature.swift
  iOS/PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift
  iOS/PixelDefinitions/pixels/subscription.json5
  iOS/PixelDefinitions/suffixes_dictionary.json5
  macOS/DuckDuckGo/Application/AppDelegate.swift
  macOS/DuckDuckGo/NetworkProtection/NetworkExtensionTargets/NetworkExtensionTargets/MacPacketTunnelProvider.swift
  macOS/DuckDuckGo/Subscription/SubscriptionManager+StandardConfiguration.swift
  macOS/DuckDuckGo/Tab/UserScripts/Subscription/SubscriptionPagesUseSubscriptionFeatureV2.swift
  macOS/LocalPackages/FeatureFlags/Sources/FeatureFlags/FeatureFlag.swift
  macOS/PixelDefinitions/pixels/subscription.json5
Labels: privacy review required

#1901 Fireproof sites sheet update
  SharedPackages/BrowserServicesKit/Sources/Common/DevicePlatform.swift
  doc-bot/import-hygiene.md
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Common/Extensions/NSViewControllerExtension.swift
  macOS/DuckDuckGo/Common/Localizables/UserText.swift
  macOS/DuckDuckGo/Common/View/AppKit/KeyEquivalentView.swift
  macOS/DuckDuckGo/Favicons/Model/FaviconManagerMock.swift
  macOS/DuckDuckGo/Fire/View/FireDialogView.swift
  macOS/DuckDuckGo/Fire/View/FirePopoverViewController.swift
  macOS/DuckDuckGo/Fireproofing/Model/FireproofDomains.swift
  macOS/DuckDuckGo/Localization/Localizable.xcstrings
  macOS/DuckDuckGo/Preferences/View/FireproofDomainCellView.swift
  macOS/DuckDuckGo/Preferences/View/FireproofDomainsViewController.swift
  macOS/LocalPackages/AppKitExtensions/Sources/AppKitExtensions/NSEventExtension.swift
  macOS/LocalPackages/Utilities/Sources/Utilities/ArrayBuilder.swift
Labels: stale
