Repository duckduckgo/apple-browsers, pull requests merged in 2025-09, with the labels that each got.

#1554 Adds a pixel for when release notes are empty
  macOS/DuckDuckGo/Statistics/GeneralPixel.swift
  macOS/DuckDuckGo/Updates/ReleaseNotesTabExtension.swift
  macOS/PixelDefinitions/pixels/update_pixels.json5
Labels: privacy review required

#1790 [iOS] Option to hide refresh in address bar
  SharedPackages/BrowserServicesKit/Sources/BrowserServicesKit/PrivacyConfig/Features/PrivacyFeature.swift
  iOS/Core/FeatureFlag.swift
  iOS/Core/PixelEvent.swift
  iOS/DuckDuckGo/AppSettings.swift
  iOS/DuckDuckGo/AppUserDefaults.swift
  iOS/DuckDuckGo/LargeOmniBarState.swift
  iOS/DuckDuckGo/MainViewController.swift
  iOS/DuckDuckGo/SettingsAppearanceView.swift
  iOS/DuckDuckGo/SettingsState.swift
  iOS/DuckDuckGo/SettingsViewModel.swift
  iOS/DuckDuckGo/SmallOmniBarState.swift
  iOS/DuckDuckGo/TabViewControllerBrowsingMenuExtension.swift
  iOS/DuckDuckGo/UserText.swift
  iOS/DuckDuckGo/en.lproj/Localizable.strings
  iOS/PixelDefinitions/pixels/browsing_menu.json5
  iOS/PixelDefinitions/pixels/settings.json5
  iOS/SharedTestUtils/Mocks/AppSettingsMock.swift
Labels: privacy review required

#1845 enable ask duck.ai by default and document pixels
  iOS/Core/FeatureFlag.swift
  iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/FlowManagers/SuggestionTrayManager.swift
  iOS/DuckDuckGo/AutocompleteViewController.swift
  iOS/DuckDuckGo/MainViewController.swift
  iOS/DuckDuckGo/SuggestionTrayViewController.swift
  iOS/DuckDuckGo/UserText.swift
  iOS/PixelDefinitions/pixels/autocomplete_click.json5
Labels: privacy review required

#1865 tap to copy version from about screen on ios
  iOS/DuckDuckGo/AboutView.swift
Labels: merge on approve

#1867 Add more metrics and diagnostics to better understand bookmarks lost structure issue
  SharedPackages/BrowserServicesKit/Sources/SyncDataProviders/Bookmarks/internal/BookmarkEntity+Syncable.swift
  SharedPackages/BrowserServicesKit/Sources/SyncDataProviders/Bookmarks/internal/BookmarksResponseHandler.swift
  SharedPackages/BrowserServicesKit/Sources/SyncDataProviders/Common/MetricsEvent.swift
  iOS/Core/BookmarksStateValidation.swift
  iOS/Core/LegacyBookmarksCoreDataStorage.swift
  iOS/Core/LegacyBookmarksStoreMigration.swift
  iOS/Core/PixelEvent.swift
  iOS/Core/SyncMetricsEventsHandler.swift
  iOS/DuckDuckGo/AppConfiguration/AppConfiguration.swift
  iOS/DuckDuckGo/AppConfiguration/PersistentStoresConfiguration.swift
  iOS/DuckDuckGo/AppLifecycle/AppStates/Foreground.swift
  iOS/DuckDuckGo/AppLifecycle/AppStates/Launching.swift
  iOS/DuckDuckGo/AppLifecycle/AppStates/Simulated.swift
  iOS/DuckDuckGo/AppLifecycle/AppStates/Terminating.swift
  iOS/DuckDuckGo/AppServices/CrashCollectionService.swift
  iOS/DuckDuckGo/BookmarksDatabaseSetup.swift
  iOS/DuckDuckGoTests/BookmarksDatabaseSetupTests.swift
  iOS/DuckDuckGoTests/BookmarksMigrationTests.swift
  iOS/DuckDuckGoTests/BookmarksStateValidationTests.swift
  iOS/PixelDefinitions/pixels/crash_pixels.json5
  macOS/DuckDuckGo/Sync/SyncMetricsEventsHandler.swift
Labels: privacy review required

#1870 iOS: New Search/Duck.ai Input Metrics - Entry Point Effectiveness
  iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/OmniBarEditingStateViewController.swift
  iOS/DuckDuckGo/AIChat/InputBox/SwitchBar/SwitchBarSubmissionMetrics.swift
  iOS/DuckDuckGoTests/SwitchBar/SwitchBarSubmissionMetricsTests.swift
  iOS/PixelDefinitions/pixels/experimental_omnibar_metrics.json5
  iOS/SharedTestUtils/Mocks/MockFeatureDiscovery.swift
Labels: privacy review required

#1888 [iOS] Add pixel to track User Notification Center Authorization Status
  iOS/Core/PixelEvent.swift
  iOS/DuckDuckGo/AppLifecycle/AppStates/Launching.swift
  iOS/DuckDuckGo/AppServices/ReportingService.swift
  iOS/DuckDuckGo/UNUserNotificationCenterRepresentable.swift
  iOS/PixelDefinitions/pixels/push-notification.json5
Labels: privacy review required

#1947 PIR: Add email confirmation decoupling pixels
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/EmailConfirmationJob.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/SubJob/BrokerProfileOptOutSubJob.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Operations/SubJob/SubJobWebRunner/BrokerProfileOptOutSubJobWebRunner.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/OptOutServices/EmailConfirmationDataService.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Pixels/DataBrokerProtectionSharedPixels.swift
  SharedPackages/DataBrokerProtectionCore/Sources/DataBrokerProtectionCore/Pixels/DataBrokerProtectionStageDurationCalculator.swift
  iOS/PixelDefinitions/pixels/data_broker_protection.json5
  macOS/PixelDefinitions/pixels/data_broker_protection.json5
Labels: privacy review required

#1954 [macOS] Fix assertion failure pixel call
  macOS/DuckDuckGo/Statistics/GeneralPixel.swift
  macOS/DuckDuckGo/Statistics/PixelKit+Assertion.swift
  macOS/PixelDefinitions/pixels/debug_assertion_failure.json5
Labels: privacy review required

#2046 Implements ThemeManager
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Common/Utilities/UserDefaultsWrapper.swift
  macOS/DuckDuckGo/Preferences/Model/AppearancePreferences.swift
  macOS/DuckDuckGo/VisualRefresh/ColorPalette.swift
  macOS/DuckDuckGo/VisualRefresh/ThemeColors.swift
  macOS/DuckDuckGo/VisualRefresh/ThemeManager.swift
  macOS/DuckDuckGo/VisualRefresh/ThemeName.swift
  macOS/DuckDuckGo/VisualRefresh/VisualStyleProviding.swift
  macOS/UnitTests/Preferences/AppearancePreferencesPersistorMock.swift
  macOS/UnitTests/Preferences/AppearancePreferencesTests.swift
  macOS/UnitTests/Sync/Mocks/MockAppearancePreferencesPersistor.swift
  macOS/UnitTests/Tab/ViewModel/TabViewModelTests.swift
  macOS/UnitTests/VisualRefresh/ThemeManagerTests.swift
Labels: enhancement
