Repository duckduckgo/apple-browsers, pull requests merged in 2025-04, with the labels that each got.

#498 Bookmark Manager UI update
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Bookmarks/Model/BookmarkManager.swift
  macOS/DuckDuckGo/Bookmarks/View/BookmarkManagementDetailViewController.swift
  macOS/DuckDuckGo/Bookmarks/ViewModel/BookmarkManagementDetailViewModel.swift
  macOS/DuckDuckGo/Bookmarks/ViewModel/BookmarksEmptyStateContent.swift
  macOS/DuckDuckGo/Common/Extensions/NSLayoutConstraintExtension.swift
  macOS/DuckDuckGo/Common/View/SwiftUI/ResizablePreviewView.swift
  macOS/DuckDuckGo/Sync/Promotion/SyncPromoView.swift
  macOS/DuckDuckGo/TabBar/View/TabBarCollectionView.swift
  macOS/UnitTests/HomePage/Mocks/MockBookmarkManager.swift
Labels: pending ship review

#541 Fix iOS ATB UI test compilation
  iOS/DuckDuckGo-iOS.xcodeproj/project.pbxproj
Labels: merge on approve

#552 macOS: Fix issues with Watch In Youtube from Duck Player
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Tab/TabExtensions/DuckPlayerTabExtension.swift
  macOS/DuckDuckGo/YoutubePlayer/DuckPlayer.swift
  macOS/UnitTests/TabExtensionsTests/DuckPlayerTabExtensionTests.swift
Labels: bug

#512 Bookmarks bar design update
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBar.storyboard
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCollectionViewItem.xib
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarViewModel.swift
  macOS/DuckDuckGo/MainWindow/MainView.swift
  macOS/DuckDuckGo/MainWindow/MainViewController.swift
  macOS/DuckDuckGo/MainWindow/MainWindowController.swift
  macOS/DuckDuckGo/NavigationBar/View/NavigationBar.storyboard
  macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
Labels: stale, pending ship review

#510 Custom bookmarks drop insertion point indicators
  macOS/DuckDuckGo-macOS.xcodeproj/project.pbxproj
  macOS/DuckDuckGo/Assets.xcassets/Images/Drop-Target-Indicator-16.imageset/Drop-Target-Indicator-16.pdf
  macOS/DuckDuckGo/Assets.xcassets/Images/Drop-Target-Indicator.imageset/Contents.json
  macOS/DuckDuckGo/Assets.xcassets/Images/Drop-Target-Indicator.imageset/Drag Marker.pdf
  macOS/DuckDuckGo/Bookmarks/View/BookmarkListInsertionIndicatorView.swift
  macOS/DuckDuckGo/Bookmarks/View/BookmarksOutlineView.swift
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBar.storyboard
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCenterAlignedLayout.swift
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCollectionViewItem.swift
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarCollectionViewItem.xib
  macOS/DuckDuckGo/BookmarksBar/View/BookmarksBarViewModel.swift
  macOS/DuckDuckGo/Common/View/AppKit/URLDragPreviewProvider.swift
  macOS/DuckDuckGo/MainWindow/MainView.swift
  macOS/DuckDuckGo/MainWindow/MainViewController.swift
  macOS/DuckDuckGo/MainWindow/MainWindowController.swift
  macOS/DuckDuckGo/NavigationBar/View/AddressBarTextEditor.swift
  macOS/DuckDuckGo/NavigationBar/View/AddressBarViewController.swift
  macOS/DuckDuckGo/NavigationBar/View/NavigationBar.storyboard
  macOS/DuckDuckGo/NavigationBar/View/NavigationBarViewController.swift
Labels: pending ship review

#504 Fix folder chooser popup font color in Bookmark popover
  macOS/DuckDuckGo/Bookmarks/View/BookmarkFolderPicker.swift
  macOS/DuckDuckGo/SecureVault/View/PopUpButton.swift
Labels: stale
